"""
Main orchestrator — runs the complete pipeline:
  1. Generate content (Gemini Pro)
  2. Generate voiceover (edge-tts)
  3. Render video (Pillow + Pygments + moviepy)
  4. Upload to YouTube Shorts
  5. Save record to MongoDB Atlas

Usage:
    python -m src.main
"""
import sys
import logging
from datetime import datetime, timezone
from pathlib import Path

# ── Configure logging ─────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s │ %(name)-18s │ %(levelname)-7s │ %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("pipeline")


def main():
    from src import config
    from src.llm import generate_content
    from src.tts import generate_speech
    from src.video import create_video
    from src.uploader_youtube import upload_to_youtube
    from src.db import save_record

    logger.info("=" * 55)
    logger.info("  Automated Coding Shorts Pipeline — Starting")
    logger.info("=" * 55)

    # ── Validate required environment variables ───────────────
    errors = []
    if not config.GEMINI_API_KEY:
        errors.append("GEMINI_API_KEY")
    if not config.MONGODB_URI:
        errors.append("MONGODB_URI")
    if errors:
        logger.error(f"Missing required secrets: {', '.join(errors)}")
        sys.exit(1)

    # Tracking record for MongoDB
    record: dict = {
        "status": "pending",
        "created_at": datetime.now(timezone.utc),
    }

    try:
        # ╔════════════════════════════════════════════════════╗
        # ║  STEP 1 — Generate Content (Gemini Pro)           ║
        # ╚════════════════════════════════════════════════════╝
        logger.info("STEP 1/5 │ Generating content with Gemini Pro...")
        content = generate_content()

        record.update({
            "topic": content["title"],
            "title": content["title"],
            "script": content["script"],
            "code": content["code"],
            "language": content["language"],
            "hashtags": content.get("hashtags", []),
        })

        logger.info(f"  ✓ Title:    {content['title']}")
        logger.info(f"  ✓ Language: {content['language']}")
        logger.info(f"  ✓ Code:     {len(content['code'])} chars, {content['code'].count(chr(10))+1} lines")
        logger.info(f"  ✓ Script:   {len(content['script'].split())} words")

        # ╔════════════════════════════════════════════════════╗
        # ║  STEP 2 — Generate Voiceover (edge-tts)           ║
        # ╚════════════════════════════════════════════════════╝
        logger.info("STEP 2/5 │ Generating voiceover with edge-tts...")
        audio_path, word_timestamps = generate_speech(
            text=content["script"],
            voice=config.TTS_VOICE,
        )

        logger.info(f"  ✓ Audio:      {audio_path}")
        logger.info(f"  ✓ Timestamps: {len(word_timestamps)} words")

        # ╔════════════════════════════════════════════════════╗
        # ║  STEP 3 — Render Video (Pillow + moviepy)         ║
        # ╚════════════════════════════════════════════════════╝
        logger.info("STEP 3/5 │ Rendering video...")
        video_path = create_video(
            code=content["code"],
            language=content["language"],
            word_timestamps=word_timestamps,
            audio_path=audio_path,
            channel_name=config.CHANNEL_NAME,
        )

        # Get video duration for record
        from src.tts import get_audio_duration
        try:
            record["duration_seconds"] = round(get_audio_duration(audio_path), 1)
        except Exception:
            record["duration_seconds"] = 0

        logger.info(f"  ✓ Video: {video_path}")

        # ╔════════════════════════════════════════════════════╗
        # ║  STEP 4 — Upload to YouTube Shorts                ║
        # ╚════════════════════════════════════════════════════╝
        logger.info("STEP 4/5 │ Uploading to YouTube Shorts...")

        # Build description: narration + newlines + hashtags
        description_parts = [
            content["script"],
            "",
            " ".join(content.get("hashtags", [])),
            "",
            f"Generated by {config.CHANNEL_NAME} pipeline",
        ]
        description = "\n".join(description_parts)

        youtube_id = upload_to_youtube(
            video_path=video_path,
            title=content["title"],
            description=description,
            tags=content.get("hashtags", []),
        )

        record["youtube_id"] = youtube_id
        if youtube_id:
            logger.info(f"  ✓ YouTube: https://youtube.com/shorts/{youtube_id}")
        else:
            logger.info("  ⚠ YouTube upload skipped (no credentials)")

        # ╔════════════════════════════════════════════════════╗
        # ║  STEP 5 — Save Record to MongoDB                  ║
        # ╚════════════════════════════════════════════════════╝
        logger.info("STEP 5/5 │ Saving record to MongoDB Atlas...")
        record["status"] = "success"
        record["published_at"] = datetime.now(timezone.utc)
        doc_id = save_record(record)

        logger.info(f"  ✓ MongoDB: {doc_id}")

        # ── Done! ─────────────────────────────────────────────
        logger.info("=" * 55)
        logger.info("  ✅  Pipeline completed successfully!")
        logger.info("=" * 55)

    except Exception as e:
        # ── Handle failure ────────────────────────────────────
        logger.error(f"Pipeline FAILED: {e}", exc_info=True)

        record["status"] = "failed"
        record["error_message"] = str(e)[:500]

        try:
            save_record(record)
            logger.info("Failure record saved to MongoDB")
        except Exception as db_err:
            logger.error(f"Could not save failure record: {db_err}")

        sys.exit(1)

    finally:
        # ── Cleanup temporary files ───────────────────────────
        _cleanup_output_dir()


def _cleanup_output_dir():
    """Remove temporary files from the output directory."""
    from src import config
    try:
        for f in config.OUTPUT_DIR.iterdir():
            if f.is_file():
                f.unlink()
                logger.debug(f"Cleaned up: {f.name}")
    except Exception as e:
        logger.warning(f"Cleanup failed (non-critical): {e}")


if __name__ == "__main__":
    main()
